### ISSUE TITLE
feat: kickstart subgraph repository for swaplace

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-subgraph#1]
The client must be installed and also an account must be registered within their API. 

We'll be looking to implement the following as the Subgraph tasks develop:
- Run local net
- Run testnet
- Run mainnet
- Prepare README.md

**Comment by RafaDSan** [comment]
Hello! I am interested in this task. I have previous experience running subgraph locally and in testnet.

**Comment by 0xneves** [comment]
This is awesome @RafaDSan !

Do you have anything done to initiate the repository? 
Have you tried to run Swaplace yet? Please let me know if you have any questions regarding it, surely I can help :D

**Comment by RafaDSan** [comment]
I do have a local node of subgraph ready and updated. 
Also, I have read the medium article. However, I couldn't find the swaplace's repository to clone it and initiate the task. Where can I find the repo? **@0xneves**

**Comment by 0xneves** [comment]
Hey @RafaDSan, I added events to the contract in commit [142f609](https://github.com/blockful-io/swaplace-contracts/commit/142f60962f3caf70363893bddc66b121ba9c4b2c)

```
    /**
     * @dev Emitted when a new swap is created.
     */
    event SwapCreated(uint256 indexed id, address indexed creator);

    /**
     * @dev Emitted when a swap is accepted.
     */
    event SwapAccepted(uint256 indexed id, address indexed accepter);

    /**
     * @dev Emitted when a swap is cancelled.
     */
    event SwapCanceled(uint256 indexed id, address indexed canceler);
```

I think you can easily test like this! 🤟 
If you think the events emitted are too simple, we can try to use the whole struct, although I don't think it will be much gas efficient (~8k more) ...
