### ISSUE TITLE
Create an issue on `swaplace-contracts` to update `hardhat.config.ts` for Subgraph usage

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-subgraph#13]
### Describe the Feature Request

This update will require that most network configurations on `hardhat.config.ts` respect a pattern within the GitHub actions as well.

Definition of Done:
- [x] Make sure the hardhat configuration is working alongside the local Docker
- [x] Make sure the GitHub actions are being respected. There is an ongoing issue where we can only test the actions by submitting PRs directly to the official repository
- [x] Create an issue describing why this change needs to happen to the `hardhat.config.ts`

**Comment by RafaDSan** [comment]
I don't think this issue is necessary right now because the `hardhat.config.ts" was already working with the docker after @0xneves modifications

**Comment by 0xneves** [comment]
Awesome, let's close this them!
