### ISSUE TITLE
feat: Migration of Ponder Homolgation Endpoint to Swaplace Production Endpoint

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/swaplace-subgraph#33]
### Describe the Feature Request
So far the Swaplace is using a temporary homologation endpoint to fetch the ponder's application data (https://rascar-swaplace-ponder-production.up.railway.app/) which is serving for tests before it's deployed into an official Swaplace endpoint.
As we are approaching a stable version of Ponder, we should start the process of migration.

### Describe Preferred Solution

Definition of Done:

- [x] Test ponder locally, it should not present any critical errors that stop the application from running,
- [x] Test ponder in the homologation endpoint, it should not present any critical errors that stop the application from running,
- [x] Configure the healthcheck of the endpoint to make sure it's correctly running and deployed
- [x] Share the new endpoint URL with the DEVs

**Comment by 0xneves** [comment]
Hey @RafaDSan , this task is almost entirely done, isn't it?

**Comment by RafaDSan** [comment]
yep, it's done actually! @0xneves
