### ISSUE TITLE
feat: adding issue template to the repository

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-subgraph#5]
Feature request:

Add the issues template to formalize issues and pull requests.

1- copy the same standard from the [swaplace-contracts](https://github.com/blockful-io/swaplace-contracts/tree/main/.github/ISSUE_TEMPLATE)
2- change the URL path to the swaplace-subgraph that is specified in the [config.yml](https://github.com/blockful-io/swaplace-contracts/blob/main/.github/ISSUE_TEMPLATE/config.yml)

**Comment by RafaDSan** [comment]
Working on this task!
