### ISSUE TITLE
refactor: remove hardhat, scripts and non necessary files from the repo

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-subgraph#7]
Refactor Request:

1- Preserve the [CODE_OF_CONDUCT.md](https://github.com/blockful-io/swaplace-subgraph/blob/main/CODE_OF_CONDUCT.md), [CONTRIBUTING.md](https://github.com/blockful-io/swaplace-subgraph/blob/main/CONTRIBUTING.md), [SECURITY.md](https://github.com/blockful-io/swaplace-subgraph/blob/main/SECURITY.md), [LICENSE](https://github.com/blockful-io/swaplace-subgraph/blob/main/LICENSE) and [README.md](https://github.com/blockful-io/swaplace-subgraph/blob/main/README.md) files.
2- Remove the remaining files from root expect [swaplace-subgraph](https://github.com/blockful-io/swaplace-subgraph/tree/main/swaplace-subgraph) folder.
3- Bring all content inside [swaplace-subgraph](https://github.com/blockful-io/swaplace-subgraph/tree/main/swaplace-subgraph) folder to the root folder.
4- Get the latest ABI from [swaplace-contracts](https://github.com/blockful-io/swaplace-contracts) by running `yarn compile` in the repo after downloading it.

**Comment by RafaDSan** [comment]
Working on this task!

**Comment by RafaDSan** [comment]
Hey @0xneves, as you said you will deploy a subgraph to be owned by the blockful, I'll provide a step-by-step!

Go to the [subgraph studio](https://thegraph.com/studio/)
Connect your wallet
Create a Subgraph
Give it a name
And follow the steps in the right corner of the site.
Obs:
When doing the command graph init --studio <name-of-the-subgraph---- you might be prompted with the "block" of the contract. Just fill it with the number block where the contract was deployed, as shown in the first transaction of the contract.

Also, reply "y" when asked if you want to mark the entities as events

Please, contact me if you have any questions!

Kind Regards,

Rafael.
